services:
  - type: web
    name: fastapi-e-commerce
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      alembic upgrade head
      python -m db.seed_db
    startCommand: uvicorn main:app
