from datetime import UTC, datetime, timedelta

from src.order.order_enums import OrderStatus

ORDERS = [
    {
        "id": 1,
        "customer_id": 1,
        "status": OrderStatus.COMPLETED,
        "total_amount": 150.00,
        "ordered_at": datetime.now(UTC) - timedelta(days=1),
    },
    {
        "id": 2,
        "customer_id": 1,
        "status": OrderStatus.PROCESSING,
        "total_amount": 75.50,
        "ordered_at": datetime.now(UTC) - timedelta(days=2),
    },
    {
        "id": 3,
        "customer_id": 2,
        "status": OrderStatus.COMPLETED,
        "total_amount": 200.00,
        "ordered_at": datetime.now(UTC) - timedelta(days=3),
    },
    {
        "id": 4,
        "customer_id": 1,
        "status": OrderStatus.COMPLETED,
        "total_amount": 120.00,
        "ordered_at": datetime.now(UTC) - timedelta(days=10),
    },
    {
        "id": 5,
        "customer_id": 2,
        "status": OrderStatus.CANCELLED,
        "total_amount": 90.00,
        "ordered_at": datetime.now(UTC) - timedelta(days=11),
    },
    {
        "id": 6,
        "customer_id": 3,
        "status": OrderStatus.COMPLETED,
        "total_amount": 180.00,
        "ordered_at": datetime.now(UTC) - timedelta(days=12),
    },
    {
        "id": 7,
        "customer_id": 1,
        "status": OrderStatus.COMPLETED,
        "total_amount": 250.00,
        "ordered_at": datetime.now(UTC) - timedelta(days=15),
    },
    {
        "id": 8,
        "customer_id": 2,
        "status": OrderStatus.COMPLETED,
        "total_amount": 300.00,
        "ordered_at": datetime.now(UTC) - timedelta(days=16),
    },
    {
        "id": 9,
        "customer_id": 3,
        "status": OrderStatus.PROCESSING,
        "total_amount": 160.00,
        "ordered_at": datetime.now(UTC) - timedelta(days=17),
    },
]

ORDER_ITEMS = [
    {
        "id": 1,
        "order_id": 1,
        "product_id": 1,
        "quantity": 2,
        "price_per_unit": 50.00,
        "total_price": 100.00,
    },
    {
        "id": 2,
        "order_id": 1,
        "product_id": 2,
        "quantity": 1,
        "price_per_unit": 50.00,
        "total_price": 50.00,
    },
    {
        "id": 3,
        "order_id": 2,
        "product_id": 3,
        "quantity": 1,
        "price_per_unit": 75.50,
        "total_price": 75.50,
    },
    {
        "id": 4,
        "order_id": 3,
        "product_id": 1,
        "quantity": 4,
        "price_per_unit": 50.00,
        "total_price": 200.00,
    },
    {
        "id": 5,
        "order_id": 4,
        "product_id": 2,
        "quantity": 2,
        "price_per_unit": 60.00,
        "total_price": 120.00,
    },
    {
        "id": 6,
        "order_id": 5,
        "product_id": 3,
        "quantity": 1,
        "price_per_unit": 90.00,
        "total_price": 90.00,
    },
    {
        "id": 7,
        "order_id": 6,
        "product_id": 1,
        "quantity": 3,
        "price_per_unit": 60.00,
        "total_price": 180.00,
    },
    {
        "id": 8,
        "order_id": 7,
        "product_id": 2,
        "quantity": 5,
        "price_per_unit": 50.00,
        "total_price": 250.00,
    },
    {
        "id": 9,
        "order_id": 8,
        "product_id": 3,
        "quantity": 3,
        "price_per_unit": 100.00,
        "total_price": 300.00,
    },
    {
        "id": 10,
        "order_id": 9,
        "product_id": 1,
        "quantity": 2,
        "price_per_unit": 80.00,
        "total_price": 160.00,
    },
]
